### ISSUE TITLE
項目の分類

### ISSUE THREAD

**Issue by degawa** [ModernFortranLocalUserGroup/CodingStyleGuide#1]
スタイルガイド作成にあたり，どのように項目を分類するか．
今は単体のルールを羅列していってもよいでしょうが，そのうちまとめる必要が出てくるかと思います．

**Comment by mmer547** [comment]
参考しようかと言っていた気象庁のコーディングスタイルの項目を貼ります。


２．スタイルルール（推奨リスト）
　フリーフォーマット（自由形式）
　１ファイルには同名のプログラム単位１つを格納
　名前
　継続記号
　字下げ（インデンテーション）
　空白
　implicit none
　１行に複数の文を書かない
　意味がわかる名称をつける
　変数の宣言方法
　引数の入出力特性
　入出力のフォーマット情報
　配列表記
　論理比較
　goto 文
３．Fortran90の機能を生かして
３．１　モジュールの使い方
　３．１．１　モジュールの３つの使用方法
　　定数参照型モジュール
　　変数参照型モジュール
　　パッケージ型モジュール
　３．１．２　定数参照型モジュール
　３．１．３　変数参照型モジュール
　３．１．４　パッケージ型モジュール
　３．１．５　モジュールの階層構造
　３．２　動的割り付け
４．禁止事項
　４．１　記憶列結合
　　EQUIVALENCE
　　COMMON
　　BLOCK DATA
　　文字長の不一致
　　ENTRY
　４．２　新機能のうち冗長なもの
　　INCLUDE
　　DO WHILE
　４．３　冗長な旧機能
　　固定形式
　　DOUBLE PRECISION
　　文字長指定 *LEN
　　data 文の行位置
　　文関数
　　組み込み手続きの個別名
　４．４　廃止予定事項
　　算術 IF 文
　　不整構造 DO 構文
　　割り当て型 GOTO 文および ASSIGN 文
　　end if 文への分岐
　　選択戻り
　　PAUSE 文
　　H 型編集記述子
　４．５　その他
　　タブ
　　処理系固有の仕様

**Comment by toya42** [comment]
>２．スタイルルール

では，基本的事項（implicit none等）を除いて，機能の推奨/制限は述べず，
>３．Fortran90の機能を生かして

を拡張して，Modernで有用な新機能をガシガシ追記していくのはいかがでしょうか．

また，ruleとtipsを混同してしまうとわかりづらくなってしまいます
tipsは別立てにすべきかもしれません

**Comment by degawa** [comment]
とりあえずはruleを整理したいところですが，役に立つのはtipsだったりするので，tipsは別扱いの方がよさそうですね．

**Comment by mmer547** [comment]
本件は長期にわたって開かれたままなので、いったんクローズしたいと思います。
