### ISSUE TITLE
各項目の書き方

### ISSUE THREAD

**Issue by degawa** [ModernFortranLocalUserGroup/CodingStyleGuide#2]
スタイルを定めるにあたって，どのような書式で書くかも定めておいた方がよいと思います．

例えば

- スタイルを定める項目名
    - ルール
- メリット
- デメリット
- 使用例

**Comment by toya42** [comment]
提案していただいた書式で良いと思います．可能な場合，類似機能・代替機能（とその長所と短所）も合わせて併記できるとさらに便利になりそうですね．
速度よりもメモリ使用量を重視したい場合とその逆など，利用者によって相反する要求はあるでしょう

**Comment by mmer547** [comment]
本件は長期間Openしたまま、賛成意見で止まっておりますので、クローズしたいと思います。
